version: '3.8'

services:
  calculator-api:
    build:
      context: .
      dockerfile: Dockerfile_Calc
    container_name: calculator-app
    restart: no
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
    volumes:
      - /home/dev/IdeaProjects/credit_bank/logs/calc:/app/logs

  deal-api:
    build:
      context: .
      dockerfile: Dockerfile_Deal
    container_name: deal-app
    restart: no
    depends_on:
      - db
      - calculator-api
      - kafka
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/deal_db
    volumes:
      - /home/dev/IdeaProjects/credit_bank/logs/deal:/app/logs

  statement-api:
    build:
      context: .
      dockerfile: Dockerfile_Statement
    container_name: statement-app
    restart: no
    depends_on:
      - deal-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    volumes:
      - /home/dev/IdeaProjects/credit_bank/logs/statement:/app/logs

  dossier-api:
    build:
      context: .
      dockerfile: Dockerfile_Dossier
    container_name: dossier-app
    restart: no
    depends_on:
      - statement-api
    ports:
      - "8095:8095"
    environment:
      - SERVER_PORT=8095
    volumes:
      - /home/dev/IdeaProjects/credit_bank/logs/dossier:/app/logs

  gateway-api:
    build:
      context: .
      dockerfile: Dockerfile_Gateway
    container_name: gateway-app
    restart: no
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
    volumes:
      - /home/dev/IdeaProjects/credit_bank/logs/gateway:/app/logs

  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=deal_db
      - POSTGRES_USER=deal_user
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    volumes:
      - deal_db:/var/lib/postgresql/data
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 10000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8099:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper

volumes:
  deal_db: