FROM bellsoft/liberica-openjdk-alpine
RUN mkdir -p /app/app
WORKDIR /app/

COPY dossier_api/target/dossier_api-0.0.1-SNAPSHOT.jar /app/

EXPOSE 8095

ENTRYPOINT ["java", "-jar", "dossier_api-0.0.1-SNAPSHOT.jar"]