FROM bellsoft/liberica-openjdk-alpine
RUN mkdir -p /app/app
WORKDIR /app/

COPY dossier_api/target/deal_api-0.0.1-SNAPSHOT.jar /app/

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "dossier_api-0.0.1-SNAPSHOT.jar"]