version: '3.8'

services:
  calculator-api:
    build:
      context: .
      dockerfile: Dockerfile_Calc
    container_name: calculator-app
    restart: no
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090


  deal-api:
    build:
      context: .
      dockerfile: Dockerfile_Deal
    container_name: deal-app
    restart: no
    depends_on:
      - db
      - calculator-api
      - zookeeper
      - kafka
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/deal_db

  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=deal_db
      - POSTGRES_USER=deal_user
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    volumes:
      - deal_db:/var/lib/postgresql/data
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

#    kafka-ui:
#      image: provectuslabs/kafka-ui
#      container_name: kafka-ui
#      ports:
#        - 8090:8080
#      restart: always
#      environment:
#        - KAFKA_CLUSTERS_0_NAME=local
#        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092,kafka2:29093
#        - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#      links:
#        - kafka
#        - kafka2
#        - zookeeper

#    producer:
#      build:
#        context: .
#        dockerfile: producer/Dockerfile_Dossier
#      ports:
#        - 8080:8080
#      links:
#        - kafka-ui
#
#    consumer:
#      build:
#        context: .
#        dockerfile: consumer/Dockerfile_Dossier
#      ports:
#        - 8081:8080
#      links:
#        - kafka-ui

volumes:
  deal_db: