version: '3.8'

services:
  calculator-api:
    build:
      context: .
      dockerfile: Dockerfile_Calc
    container_name: calculator-app
    restart: no
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090


  deal-api:
    build:
      context: .
      dockerfile: Dockerfile_Deal
    container_name: deal-app
    restart: no
    depends_on:
      - db
      - calculator-api
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/deal_db

  statement-api:
    build:
      context: .
      dockerfile: Dockerfile_Statement
    container_name: statement-app
    restart: no
    depends_on:
      - deal-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=deal_db
      - POSTGRES_USER=deal_user
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    volumes:
      - deal_db:/var/lib/postgresql/data
    restart: always

volumes:
  deal_db: