spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/deal_db
    username: deal_user
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: off
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

#  cloud:
#    openfeign:
#      client:
#        config:
#          calc:
#            url: http://localhost:8090/calculator/offers
#            connect-timeout: 1000
#            read-timeout: 2000
#
#      oauth2:
#        enabled: true

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic

server:
  port: 8080
#feign:
#  autoconfiguration:
#    jackson:
#      enabled: true
