server:
  port: 8000

logging:
  file:
    name: logs/log_gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      routes:
#        - id: calculator
#          uri: http://calc-app:8090
#          predicates:
#            - Path=/calculator/**
        - id: deal
          uri: http://deal-app:8085
          predicates:
            - Path=/deal/**
        - id: statement
          uri: http://statement-app:8080
          predicates:
            - Path=/statement/**