server:
  port: 8095
spring:
  application:
    name: Neo-credit-bank
  mail:
    host: smtp.yandex.ru
    username: ProkofevaMariyaS@yandex.ru
    password: iwkeziltzbifnllg
    port: 465
    protocol: smtps

mail:
  debug: true

deal_feignclient_url: http://deal-app:8085/deal/
#deal_feignclient_url: http://localhost:8085/deal/