server:
  port: 8095
spring:
  mail:
    host: smtp.yandex.ru
    username: ProkofevaMariyaS@yandex.ru
    password: iwkeziltzbifnllg
    port: 465
    protocol: smtps
  kafka:
    bootstrap-servers: kafka:29092, localhost:29092

mail:
  debug: true

deal_feignclient_url: http://deal-app:8085/deal/
#deal_feignclient_url: http://localhost:8085/deal/

logging:
  file:
    name: logs/log_dossier

kafka:
  topics:
    topicFinReg: finish-registration
    topicCreateDoc: create-documents
    topicSendDoc: send-documents
    topicSendSes: send-ses
    topicCreditIssued: credit-issued
    topicDenied: statement-denied