name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
#          fail_ci_if_error: true # optional (default = false)
#          files: ./coverage1.xml,./coverage2.xml # optional
#          flags: unittests # optional
#          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
#          verbose: true # optional (default = false)