name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
#          directory: ./coverage/reports/
#          env_vars: OS,PYTHON
#          fail_ci_if_error: true
#          files: ./coverage1.xml,./coverage2.xml,!./cache
#          flags: unittests
#          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
#          verbose: true